//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTrongBinh2210900004_Demo_Ontap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranTrongBinh2210900004_Demo_OnTapEntities : DbContext
    {
        public TranTrongBinh2210900004_Demo_OnTapEntities()
            : base("name=TranTrongBinh2210900004_Demo_OnTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ttb_SACH> Ttb_SACH { get; set; }
        public virtual DbSet<Ttb_TACGIA> Ttb_TACGIA { get; set; }
    }
}
