//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTrongBinh2210900004_Demo_Ontap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ttb_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ttb_TACGIA()
        {
            this.Ttb_SACH = new HashSet<Ttb_SACH>();
        }
    
        public string Ttb_MaTG { get; set; }
        public string Ttb_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ttb_SACH> Ttb_SACH { get; set; }
    }
}
