//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTrongBinh2210900004_Demo_Ontap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ttb_SACH
    {
        public string Ttb_MaSach { get; set; }
        public string Ttb_TenSach { get; set; }
        public Nullable<int> Ttb_SoTrang { get; set; }
        public Nullable<int> Ttb_NamXB { get; set; }
        public string Ttb_MaTG { get; set; }
        public Nullable<bool> Ttb_TrangThai { get; set; }
    
        public virtual Ttb_TACGIA Ttb_TACGIA { get; set; }
    }
}
